name: Create Semver Version Tag

on: 
  pull_request_target:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  create-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      NEW_TAG: ${{ steps.generate-tag.outputs.NEW_TAG }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        
      - name: Get major version from setup.py
        id: get-major
        run: |
          if [ ! -f setup.py ]; then
            echo "Error: setup.py not found"
            exit 1
          fi
          
          major_version=$(grep -oP "version='\K\d+" setup.py || echo "")
          
          if [ -z "$major_version" ]; then
            echo "Error: Could not find valid major version in setup.py"
            echo "Current directory: $(pwd)"
            echo "Files in directory: $(ls -la)"
            exit 1
          fi
          
          echo "Found major version: $major_version"
          echo "MAJOR_VERSION=$major_version" >> $GITHUB_ENV
        
      - name: Count merged PRs
        id: count-prs
        run: |
          # Use GitHub API to get merged PRs
          pr_count=$(gh api graphql -f query='
            query($owner:String!, $repo:String!) {
              repository(owner:$owner, name:$repo) {
                pullRequests(states:MERGED, baseRefName:"main") {
                  totalCount
                }
              }
            }' -f owner="${{ github.repository_owner }}" -f repo="${{ github.event.repository.name }}" | jq '.data.repository.pullRequests.totalCount')
          
          echo "Total merged PRs to main: $pr_count"
          echo "MINOR_VERSION=$pr_count" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Count commits in PR branch
        id: count-commits
        run: |
          base_commit=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          commit_count=$(git rev-list --count $base_commit..${{ github.event.pull_request.head.sha }})
          
          if [ -z "$commit_count" ] || [ "$commit_count" -eq "0" ]; then
            commit_count="1"
          fi
          
          echo "Revision count calculated as: $commit_count"
          echo "REVISION=$commit_count" >> $GITHUB_ENV
      
      - name: Generate new tag
        id: generate-tag
        run: |
          if [[ -z "$MAJOR_VERSION" ]]; then
            echo "Error: MAJOR_VERSION not set"
            exit 1
          fi

          if [[ -z "$MINOR_VERSION" ]]; then
            echo "Error: MINOR_VERSION not set"
            exit 1
          fi

          if [[ -z "$REVISION" ]]; then
            echo "Error: REVISION not set"
            exit 1
          fi
          
          new_tag="${MAJOR_VERSION}.${MINOR_VERSION}.${REVISION}"
          echo "Generated tag: $new_tag"
          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV
          echo "::set-output name=NEW_TAG::$new_tag"

      - name: Update setup.py
        run: |
          # Create backup
          cp setup.py setup.py.bak
          
          # Update version in setup.py
          if [[ "$OSTYPE" == "darwin"* ]]; then
            # macOS version of sed
            sed -i '' 's/version="[^"]*"/version="$NEW_TAG"/g' setup.py
            sed -i '' "s/version='[^']*'/version='$NEW_TAG'/g" setup.py
          else
            # Linux version of sed
            sed -i 's/version="[^"]*"/version="NEW_TAG"/g' setup.py
            sed -i "s/version='[^']*'/version='$NEW_TAG'/g" setup.py
          fi
          
          echo "Updated setup.py contents:"
          cat setup.py
        
      - name: Commit and push setup.py changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add setup.py
          git commit -m "Update version to $NEW_TAG"
          git push origin HEAD:main
      
      - name: Create and push tag
        run: |
          if [[ ! "$NEW_TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Invalid tag format: $NEW_TAG"
            exit 1
          fi
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          
          git tag -a "v$NEW_TAG" -m "Release v$NEW_TAG
          
          Major: Controlled via setup.py
          Minor: PR #$MINOR_VERSION since last major version
          Revision: $REVISION commits in this PR"
          
          git push origin "v$NEW_TAG"

  update-staging:
    needs: create-tag
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: staging

      - name: Update version in setup.py
        run: |
          # confirm that NEW_TAG exists
          if [ -z "${{ needs.create-tag.outputs.NEW_TAG }}" ]; then
            echo "Error: NEW_TAG not set"
            exit 1
          fi

          # Create backup
          cp setup.py setup.py.bak
          
          # Update version in setup.py
          if [[ "$OSTYPE" == "darwin"* ]]; then
            # macOS version of sed
            sed -i '' 's/version="[^"]*"/version="${{ needs.create-tag.outputs.NEW_TAG }}"/g' setup.py
            sed -i '' "s/version='[^']*'/version='${{ needs.create-tag.outputs.NEW_TAG }}'/g" setup.py
          else
            # Linux version of sed
            sed -i 's/version="[^"]*"/version="${{ needs.create-tag.outputs.NEW_TAG }}"/g' setup.py
            sed -i "s/version='[^']*'/version='${{ needs.create-tag.outputs.NEW_TAG }}'/g" setup.py
          fi
          
          echo "Updated setup.py contents:"
          cat setup.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add setup.py
          git commit -m "Update version to ${{ needs.create-tag.outputs.NEW_TAG }}"
          git push origin HEAD:staging